[package]
name = "imessage-cli"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "msg"
path = "src/main.rs"


[dependencies]

clap = "3.1.4"
strsim = "0.10.0"
log = "0.4"
simple_logger = "4.0"
regex = "1"
ascii_converter = "0.3.0"
cow-utils = "0.1.3"
term_size = "0.3.2"